# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d78f49ca0b9f5397b3bc4eb5162362922bb6e13f37989f001286b0f22d18155eb82a7edc83916e28dd737c451b1dbe0d6b792f12116f41efdc298cd2a2f69cb7

test:
  secret_key_base: 66b31915e4b749e4ccf20e753b96911aad3e8a0f07fbbfe58f167ae9c89aef04c3425d02691ead076ca0cd8e4e3afc4059d4b448734f7869cd6f9def08eae765

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
